version: '3.8'

services:
  bitlbee:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/mbologna/docker-bitlbee:latest
    container_name: bitlbee
    restart: unless-stopped
    ports:
      - "6667:6667"
    volumes:
      - ./data:/var/lib/bitlbee
    user: "${UID}:${GID}" # Needed for VOLUME permissions
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "6667" ]
      interval: 30s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bitlbee-net
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: "1.0"
        reservations:
          memory: 256m

  stunnel:
    image: docker.io/dweomer/stunnel:latest
    container_name: bitlbee-stunnel
    restart: always
    ports:
      - "16697:6697"
    environment:
      - STUNNEL_SERVICE=bitlbee-stunnel
      - STUNNEL_ACCEPT=6697
      - STUNNEL_CONNECT=bitlbee:6667
    depends_on:
      - bitlbee
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "6697" ]
      interval: 30s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bitlbee-net
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "1.0"
        reservations:
          memory: 128m

networks:
  bitlbee-net:
    driver: bridge
