apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitlbee
  namespace: bitlbee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitlbee
  template:
    metadata:
      labels:
        app: bitlbee
    spec:
      containers:
        - name: bitlbee
          image: docker.io/mbologna/docker-bitlbee:latest
          ports:
            - containerPort: 6667
          volumeMounts:
            - mountPath: /var/lib/bitlbee
              name: bitlbee-data
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "6667"
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "6667"
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: bitlbee-data
          persistentVolumeClaim:
            claimName: bitlbee-pvc
