apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitlbee-stunnel
  namespace: bitlbee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitlbee-stunnel
  template:
    metadata:
      labels:
        app: bitlbee-stunnel
    spec:
      containers:
        - name: stunnel
          image: docker.io/dweomer/stunnel:latest
          ports:
            - containerPort: 6697
          envFrom:
            - configMapRef:
                name: stunnel-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "1"
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "6697"
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - nc
                - -z
                - localhost
                - "6697"
            initialDelaySeconds: 10
            periodSeconds: 30
